### ISSUE TITLE
Mobile first?

### ISSUE THREAD

**Issue by chelseadole** [marco-zangari/portfolio#15]
https://github.com/marco-zangari/portfolio/blob/51d111337bbcec7476037c6b370f9f4d119e6e53/styles/base.css#L1

in modules, add @media queries so that your default viewing is mobile. Adding @media queries for sizes bigger than phone/laptop (min size, instead of max size!) mean it's mobile-first 👍

**Comment by marco-zangari** [comment]
addd media query to layout.css
